AWSTemplateFormatVersion: 2010-09-09
Description: VPC template
# Resources section
Resources:
  myVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
       - Key: Name
         Value: IBM-VPC

  myInternetGateway:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
      - Key: Name
        Value: IBM-IGW

  AttachGateway:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId:
         Ref: myVPC
      InternetGatewayId:
         Ref: myInternetGateway


  myPubSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref myVPC
      CidrBlock: 10.0.0.0/20
      AvailabilityZone: "us-east-1a"
      Tags:
      - Key: Name
        Value: Ibm-app-sub

  myPvtSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref myVPC
      CidrBlock: 10.0.16.0/20
      AvailabilityZone: "us-east-1b"
      Tags:
      - Key: Name
        Value: Ibm-db-sub

  myPubRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: myVPC
      Tags:
      - Key: Name
        Value: Ibm-app-rt

  myPvtRouteTable:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId:  
        Ref: myVPC
      Tags:
      - Key: Name
        Value: Ibm-db-rt

  myPubSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: myPubSubnet
      RouteTableId:
        Ref: myPubRouteTable

  myPvtSubnetRouteTableAssociation:
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      SubnetId:
        Ref: myPvtSubnet
      RouteTableId:
        Ref: myPvtRouteTable

  MyIGWRoute:
    Type: AWS::EC2::Route
    Properties:
      RouteTableId: !Ref myPubRouteTable
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref  myInternetGateway
